export const GET_USER = 'GET_USER';
export const USER_SELECT = 'USER_SELECT';
export const GET_PATIENTS_LIST = 'GET_PATIENTS_LIST';
export const SET_PATIENT_SELECTED = 'SET_PATIENT_SELECTED';
export const GET_PATIENT_PERSONAL_DATA = 'GET_PATIENT_PERSONAL_DATA';
export const GET_CHAT_PATIENT_TARGET = 'GET_CHAT_PATIENT_TARGET';
export const SET_GET_CHAT_PATIENT_TARGET = 'SET_GET_CHAT_PATIENT_TARGET';
